name: tsella
favicon: null
layout_spectrum: 0.246861825697124
typography_spectrum: 0.9930439074523747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9251479241065681
  lightness: 0.36706318659707904
  saturation: 0.365733620012179
  rhythmicContrast: 0.9524458067025989
purpose: []
